### ISSUE TITLE
Add option to remove "kanata-tray" from menu icons in MacOS or use Kanata icon in its place

### ISSUE THREAD

**Issue by jakemayfield** [rszyma/kanata-tray#21]
Possible bug or enhancement needed.

Is "kanata-tray" supposed to show up in the menu bar instead of the kanata icon? If so, it takes up too much room in the menu bar in MacOS. I would prefer to see the kanata icon in its place or have the option to show only our layer icons.

<img width="608" alt="Screenshot 2024-05-01 at 10 42 59 AM" src="https://github.com/rszyma/kanata-tray/assets/14812609/d2672d8e-8cda-4adc-84ed-c81355317905">

Thank you for creating this. Loving it so far.

**Comment by rszyma** [comment]
> Is "kanata-tray" supposed to show up in the menu bar instead of the kanata icon? If so, it takes up too much room in the menu bar in MacOS. I would prefer to see the kanata icon in its place or have the option to show only our layer icons.

You could try removing either of these lines and see if the text get removed https://github.com/rszyma/kanata-tray/blob/aa300be276806d09b3b101c00a566a487b669d08/app/app.go#L44-L45

**Comment by guruor** [comment]
Removing title works, I think this should be default behaviour. Icon and tooltip should be sufficient. I can make a PR if this can be default.


This is how it looks on mac:
<img width="148" alt="Screenshot 2024-05-28 at 8 51 38 PM" src="https://github.com/rszyma/kanata-tray/assets/14184045/bc62f77b-729b-4723-aecf-5f9df86300e6">
