### ISSUE TITLE
Use XDG config path for macOS instead

### ISSUE THREAD

**Issue by jussapaavo** [rszyma/kanata-tray#25]
Regarding:
```
The config folder location:
* Linux ~/.config/kanata-tray.
* Windows C:\Users\<YourUsername>\AppData\Roaming\kanata-tray
* macOS $HOME/Library/Application\ Support/kanata-tray
```

Is it possible to use the same XDG config path spec as in Linux for macOS also? I think it would make more sense, as it is used by other utilities as well. It would make organizing and managing the configs via dotfiles more straight forward. For example, utilities like kitty, Raycast and gcloud use `~/.config/` path.

At least, would it be possible to set or customize this via environment variables, like `KANATA_TRAY_CONFIG` etc.

**Comment by rszyma** [comment]
The config dir path is standard for macos, so I wouldn't change it by default. You should be already be able to change config dir location by setting XDG_CONFIG_HOME env var. If that doesn't work for you, there's also command line option to set any path you want.

**Comment by rszyma** [comment]
Actually, there's no cli option for setting config (yet, I thought I added it), but still, you should be able to set XDG_CONFIG_HOME to change config dir like this:
```bash
XDG_CONFIG_HOME=/path/to/custom/config/dir kanata-tray
```

**Comment by jussapaavo** [comment]
I suppose using `~/Library/Application Support/` is the default only for installed apps but not for cli utilities that run from the terminal. I've never seen any other cli utility using Application Support, instead they either create their own hidden config dir in $HOME (like vscode, docker, aws, etc)  or use `~/.config/` (like previously mentioned Google Cloud, kitty, Raycast, etc).

**Comment by jussapaavo** [comment]
> Thta default config dir path is standard for macos, so I wouldn't change it's default to not go off spec. You should be already be able to change config dir location by setting XDG_CONFIG_HOME env var. If that doesn't work for you, there's also command line option to set any path you want.


I suppose using ~/Library/Application Support/ is the default only for installed apps but not for cli utilities that run from the terminal. I've never seen any other cli utility using Application Support, instead they either create their own hidden config dir in $HOME (like vscode, docker, aws, etc) or use ~/.config/ (like previously mentioned Google Cloud, kitty, Raycast, etc).

**Comment by jussapaavo** [comment]
> Actually, there's no cli option for setting config (yet, I thought I added it), but still, you should be able to set XDG_CONFIG_HOME to change config dir like this:
> 
> ```shell
> XDG_CONFIG_HOME=~/.config kanata-tray
> ```

Anyway, I tried to set this but it didn't work. `kanata-tray` still uses the configs from the old path and not the specified by `$XDG_CONFIG_HOME`.

**Comment by rszyma** [comment]
Looking at implementation in `configdir` go library which we use, XDG_CONFIG_HOME doesn't apply to macos. https://github.com/kirsle/configdir/blob/e45d2f54772fea5426e7ce417474b62da9457dcc/config_darwin.go#L13. Let's just add a custom env variable.

**Comment by jussapaavo** [comment]
Nice, thanks for the fast response. Appreciate it.
