### ISSUE TITLE
[MacOS] KANATA_TRAY_CONFIG_DIR not being respected

### ISSUE THREAD

**Issue by schinwald** [rszyma/kanata-tray#29]
![image](https://github.com/user-attachments/assets/7ff8d12d-29e7-489d-8669-92d2fa50e597)

Not sure if I'm doing this right, but for some reason any time I try to load the environment variable with the macos executable in the latest release, it's not using the correct config path. Any ideas why this could be?

**Comment by rszyma** [comment]
Are you using the latest version?

**Comment by schinwald** [comment]
![image](https://github.com/user-attachments/assets/7e36517c-24ba-4a1a-bf03-4b5c5f519280)

I believe so

**Comment by rszyma** [comment]
0.3.2 doesn't include the commit that added env var, you have to compile from latest git for now, or wait for next release (I'll create release later today or tomorrow, if i don't foeget)

**Comment by schinwald** [comment]
Ahhhh okay that makes sense! Thanks for the clarification and help!

**Comment by rszyma** [comment]
https://github.com/rszyma/kanata-tray/releases/tag/v0.4.0
