### ISSUE TITLE
Release binary from v0.5.1 tries to write log in /usr/bin/local

### ISSUE THREAD

**Issue by sakuragasaki46** [rszyma/kanata-tray#40]
I downloaded the binary from the releases tab, and moved it to `/usr/local/bin`.

The issue is, when trying to run the command, it exits immediately, due to it not being capable to write the log file, and it tries to write it **in the same directory as the executable**.

```sh
$ kanata-tray-linux 
{"time":"2024-12-04T17:08:36.455771192+01:00","level":"ERROR","prefix":"-","file":"main.go","line":"44","message":"kanata-tray exited with an error: failed to create kanata_tray_lastrun.log file: open /usr/local/bin/kanata_tray_lastrun.log: permission denied"}
```

There is no documented option to change the log file in the README, either.

**Comment by rszyma** [comment]
Added env var so you can choose some other folder, and created new release https://github.com/rszyma/kanata-tray/releases/tag/v0.5.2

**Comment by sakuragasaki46** [comment]
Thanks for the bug fix, however, I want the log directory to be configurable separately from the config directory (i.e. `/var/log/kanata-tray`). Is that possible? Will it be added possibly in a future release? (i.e. by adding a new entry in `kanata-tray.toml`)

**Comment by rszyma** [comment]
Use KANATA_TRAY_LOG_DIR, not KANATA_TRAY_CONFIG_DIR

**Comment by rszyma** [comment]
Ah i see where you coming from - the commit message is wrong. (But the change itself is correct) I'll fix the commit message later (probably)
