### ISSUE TITLE
Error for kanata config file `.../kanata.kbd`: file doesn't exist

### ISSUE THREAD

**Issue by reidprichard** [rszyma/kanata-tray#7]
First off, love the project! I didn't realize this existed - wish it were more prominently advertised on Kanata's github, as having to deal with Task Scheduler/systemd to run Kanata in the background can be an obstacle to some. Having something you can just double-click is great.

This doesn't appear to affect the actual functionality of kanata-tray, but when running from the command line on Linux I get: "Error for kanata config file '/home/reid/.config/kanata/kanata.kbd': file doesn't exist". My config is pretty minimal so I don't think it's a PEBCAK error, but I've been having a lot of those lately:
```
configurations = [
	"/path/to/my/config/gmmk_kanata.kbd"    
]

executables = [
	"~/.local/bin/kanata_cmd_allowed"
]

[layer_icons]

[general]
include_executables_from_system_path = true
include_configs_from_default_locations = false
launch_on_start = true
```

**Comment by rszyma** [comment]
> First off, love the project! I didn't realize this existed - wish it were more prominently advertised on Kanata's github, as having to deal with Task Scheduler/systemd to run Kanata in the background can be an obstacle to some. Having something you can just double-click is great.

Thank you for the kind words!

The bug is a simple copy-paste error, I'll fix soon.
